version: '3.8'

services:
  # 1. Tu API de .NET
  - type: web
    name: caverosalud-api
    runtime: docker
    repo: https://github.com/mariaquispecc/caveroSalud-Digital
    plan: free
    region: virginia
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      # Conexión automática: Toma los datos de la base de datos creada abajo
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: caverosalud-db
          property: connectionString

# 2. Tu Base de Datos Postgres en la nube
databases:
  - name: caverosalud-db
    databaseName: cavero
    user: postgres
    plan: free
    region: virginia