services:
  # 1. Tu API de .NET
  - type: web
    name: clinicaCavero
    runtime: docker
    plan: free
    region: Virginia 
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      # Conexión automática: Toma los datos de la base de datos creada abajo
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: caverosaludBD
          property: connectionString

# 2. Tu Base de Datos Postgres en la nube
databases:
  - name: caverosaludBD
    databaseName: cavero
    user: postgres
    plan: free
    region: Virginia 
