namespace CaveroSalud.Features.Authentication.DTOs
{
    public class AdminCreateUserDto
    {
        public string FullName { get; set; }
        public string Dni { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Role { get; set; }
        public string Speciality { get; set; }
        // Temporary password generated by admin or system
        public string TemporaryPassword { get; set; }
    }
}
